set -g prefix C-a
unbind C-b
bind C-a last-window

setw -g mode-keys vi
bind -t vi-copy 'v' begin-selection
bind -t vi-copy 'y' copy-selection
unbind p
bind p paste-buffer

bind h select-pane -L
bind k select-pane -U
bind l select-pane -R
bind j select-pane -D

set -g mode-mouse on
setw -g mouse-select-window on
setw -g mouse-select-pane on

set -g default-terminal "screen-256color"


