call plug#begin()

Plug 'suan/vim-instant-markdown', {'for': 'markdown'}
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-ragtag'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-fugitive'
Plug 'christoomey/vim-system-copy'
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-entire'
Plug 'masukomi/vim-markdown-folding'

" Color shemes
Plug 'rafi/awesome-vim-colorschemes'
Plug 'kristijanhusak/vim-hybrid-material'
Plug 'dikiaap/minimalist'
" end Color shemes

Plug 'ryanoasis/vim-devicons'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

call plug#end()

set noswapfile " отключаем создание .swap файлов
set number
syntax on
set tabstop=2  shiftwidth=2 softtabstop=2 smarttab expandtab smartindent
set ruler
" Cтрока ниже нужна для того что бы в нормальном режиме работали английская раскладка
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯЖ;ABCDEFGHIJKLMNOPQRSTUVWXYZ:,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz
filetype plugin indent on
set backspace=indent,eol,start
set complete-=i
set nocompatible " откл совместимости с Vi
set hlsearch    " включаем подсветку слов при поиске;
set incsearch   " улучшаем видимость подсветки слов при поиске;
set ignorecase
set smartcase
set showmatch
set gdefault
set cursorline
set t_Co=256
set t_ut=
set wrap
set linebreak
" set textwidth=79
" set colorcolumn=85
" set formatoptions+=t
set scrolloff=5
set hidden
set history=1000
:silent call system('mkdir -p ~/.vim/tmp')
set directory^=~/.vim/tmp//
set writebackup
set background=dark
" set termguicolors
"colorscheme codedark
"colorscheme dracula
"colorscheme orbital
" colorscheme paramount
"colorscheme hybrid_reverse
colorscheme minimalist
highlight NonText guifg=bg
highlight Comment cterm=italic gui=italic
let g:mapleader=","
nnoremap ; :

" Перереопределяем клавиши j k для лучшего перехода по переносимым строкам
noremap j gj
noremap k gk

" Отключение подсветки найденных совпадений в файле
nmap <CR> :nohlsearch<cr>

" Для лучшего поиска по фаилам и катологам с помощью :find
" А так же для поиска по буферам :b
set path+=**
set wildmenu

" C-tags Создает фал tags. Можно найти определение ф-ции в проекте
" Перед использованием в консоли vim :!ctags -R .
" USe Ctrl+] to jump to tag under cursor
" USe g+Ctrl+] for ambiguous tag
" USe Ctrl+t to jump back up the tag stack
command! MakeTags !ctags -R .

"Autocomplete - documentation |:help ins-completion|
" Ctrl+n or ^n. ^ - Ctrl
" Ctrl+p back search
" - ^x^n автокомплит только из текущего файла
" - ^x^f автокомплит пути к файлу
" - ^x^] автокоплит по ctags
" Переделаем на кнопку Tab
" imap <Tab> <C-n>

" FILE BROWSING:
" Применение
" - :edit - открывает текущую папку в файловом менеджере
" - <CR>/v/t - открывает фаил - гориз_сплит/верт_сплит/таб
" - check |netrw-browse-maps| for more mappings
" - % - create new file in current drectory
" НАСТРОЙКИ:
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in previous window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=',\(^\|\s\s\)\zs\.\S\+'
let g:netrw_winsize=15
let g:netrw_hide=0
" augroup ProjectDrawer
"   autocmd!
"   autocmd VimEnter * :Vexplore .
" augroup END
" Назначим клавиши
" nmap <leader>f :edit .<cr>
" nmap <leader>f :Vexplore .<cr>
" Open file browsers buffer
" nnoremap ,n :buffers<CR>:buffer <Space>
"nnoremap bb :buffers<CR>:buffer <Space>
" Search file
"nmap ff :find<Space>

"Команды VIM
" :helpgerp windows - просмотр всего help что связанно с windows
" "ad - удалить в буфер 'a'
" "ap - вставить из буфера 'a'
" "+yy - копировать в буфер обмена

" Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

" Set line number
set number relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" WINDOWS
" force minimum window width
" автоматический ресайз сплита окна
set winwidth=130
" Resize window split
"nnoremap <leader>v :vertical resize 150<cr>
"nnoremap <leader>h :resize 40<cr>

" Jump to windows
nmap <C-J> <C-W><C-J> " ctrl-j (вместо ctrl-W-J)
nmap <C-K> <C-W><C-K> " ctrl-K (вместо ctrl-W-K)
nmap <C-H> <C-W><C-H> " ctrl-H (вместо ctrl-W-H)
nmap <C-L> <C-W><C-L> " ctrl-L (вместо ctrl-W-L)
" Maximize current split horizontally and vertically
map <F5> <C-W>_<C-W><Bar>

" Отключяю стрелки
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
" inoremap <up> <nop>
" inoremap <down> <nop>
" inoremap <left> <nop>
" inoremap <right> <nop>

" Отключаем F1 help
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" Autosave при нажатии Esc
inoremap <Esc> <Esc>:w<cr>
nnoremap <Esc> <Esc>:w<cr>

" Открыть vimrc в окне справа
nnoremap <leader>v <C-w><C-v><C-l>:e $MYVIMRC<cr>

" Разбить окно по вертикали
"nnoremap <leader>w <C-w>v<C-w>l
nnoremap <leader>w :rightb vnew<cr>

" Only current window
nnoremap <leader>o :only<cr>

" Vim-markdown-folding
" zo - open one
" zc - close one
" zr - open all
" zm - close all
set nocompatible
if has("autocmd")
  filetype plugin indent on
endif
" Set tree in heading
"autocmd FileType markdown set foldexpr=NestedMarkdownFolds()

" fzf-vim color settings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-s': 'split',
  \ 'ctrl-v': 'vsplit' }
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'Type'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Character'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" LightLine settings
" always display status line
set laststatus=2
" do not show mode
set noshowmode
" define lightline configuration
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ }


" Fzf search keymap
nmap fb :Buffers<cr>
nmap ff :Files<cr>
nmap fc :Colors<cr>

" NerdTree keymap
map <leader>f :NERDTreeToggle<cr>

" Find and replace based on word under cursor
nnoremap <Leader>s :%s/\<<C-r><C-w>\>//g<Left><Left>

" Change cursor view
let &t_SI.="\e[5 q" "SI = INSERT mode
let &t_SR.="\e[4 q" "SR = REPLACE mode
let &t_EI.="\e[1 q" "EI = NORMAL mode (ELSE)

" Status line
set laststatus=2
" Dictionary: take mode() input -> longer notation of current mode
" mode() is defined by Vim
let g:currentmode={ 'n' : 'Normal ', 'no' : 'N·Operator Pending ', 'v' : 'Visual ', 'V' : 'V·Line ', '^V' : 'V·Block ', 's' : 'Select ', 'S': 'S·Line ', '^S' : 'S·Block ', 'i' : 'Insert ', 'R' : 'Replace ', 'Rv' : 'V·Replace ', 'c' : 'Command ', 'cv' : 'Vim Ex ', 'ce' : 'Ex ', 'r' : 'Prompt ', 'rm' : 'More ', 'r?' : 'Confirm ', '!' : 'Shell ', 't' : 'Terminal '}


" Function: return current mode
" abort -> function will abort soon as error detected
function! ModeCurrent() abort
    let l:modecurrent = mode()
    " use get() -> fails safely, since ^V doesn't seem to register
    " 3rd arg is used when return of mode() == 0, which is case with ^V
    " thus, ^V fails -> returns 0 -> replaced with 'V Block'
    let l:modelist = toupper(get(g:currentmode, l:modecurrent, 'V·Block '))
    let l:current_status_mode = l:modelist
    return l:current_status_mode
endfunction

function! GitBranch()
  return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

function! StatuslineGit()
  let l:branchname = GitBranch()
  return strlen(l:branchname) > 0?'  '.l:branchname.' ':''
endfunction

function! Precent()
  return '%'
endfunction

hi User1 ctermbg=233  ctermfg=140   guibg=green guifg=red
hi User2 ctermbg=233  ctermfg=blue  guibg=red   guifg=blue
hi User3 ctermbg=233  ctermfg=green guibg=blue  guifg=green
hi User4 ctermbg=233  ctermfg=167   guibg=blue  guifg=green 

set statusline=
set statusline+=%#function# " Задаем цвет из цветовой схемы vim
set statusline+=%2*\ %{ModeCurrent()}
set statusline+=%2*\ %*
set statusline+=%3*\ ‹‹
set statusline+=%3*\ %f%*
set statusline+=%3*\ ››
set statusline+=%3*\ %y
set statusline+=%4*\ %m
set statusline+=%1*\%#keyword#\%1*\ %F
set statusline+=%1*\%=
set statusline+=%1*\ %{StatuslineGit()}
set statusline+=%1*\ ‹‹
set statusline+=%1*\ %{strftime('%R',getftime(expand('%')))}
set statusline+=%2*\ [
set statusline+=%2*\#%n
set statusline+=%2*\]
set statusline+=%1*\ %r%w\%P
set statusline+=%1*\ ››\ %*


