#! /bin/sh

#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/

###################
## configuration ##
###################

## workspace name
## font needed wuncon-siji
bspc monitor -d   '' '' '' '' '' '' '' ''

## common bspwm configuration
bspc config border_width        2
bspc config window_gap         	16
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config top_padding          34
bspc config bottom_padding       0


## color settings
#bspc config focused_border_color "#d8dee8"
#bspc config focused_border_color "#787e68"
bspc config focused_border_color "#009688"

#bspc config normal_border_color "#2f343f"
bspc config normal_border_color "#08090a"

##################
## window rules ##
##################

## workspace 1 (labs)
bspc rule -a URxvt desktop='^1' follow=on focus=on
bspc rule -a Tilix desktop='^1' follow=on focus=on

## workspace 2 (web browsers)
bspc rule -a Firefox-esr desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on
bspc rule -a Opera desktop='^2' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^2' follow=on focus=on

## workspace 3 (file-manager)
bspc rule -a pcmanfm desktop='^3' follow=on focus=on
bspc rule -a File-roller desktop='^3' follow=on focus=on

## workspace 4 (text-editors)
bspc rule -a Geany desktop='^4' follow=on focus=on
bspc rule -a libreoffice-startcenter desktop='^4' follow=on focus=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a Soffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-base desktop='^4' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^4' follow=on focus=on
bspc rule -a libreoffice-draw desktop='^4' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^4' follow=on focus=on
bspc rule -a libreoffice-math desktop='^4' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^4' follow=on focus=on
bspc rule -a Wps desktop='^4' follow=on focus=on
bspc rule -a Et desktop='^4' follow=on focus=on
bspc rule -a Wpp desktop='^4' follow=on focus=on

## workspace 5 (graphic-utilities)
bspc rule -a Nitrogen desktop='^5' follow=on focus=on
bspc rule -a Font-manager desktop='^5' state=tiled follow=on focus=on
bspc rule -a Evince desktop='^5' follow=on focus=on
bspc rule -a Gucharmap desktop='^5' follow=on focus=on

## workspace 6 (multimedia)
bspc rule -a Audacity desktop='^6' follow=on focus=on
bspc rule -a Vlc desktop='^6' follow=on focus=on
bspc rule -a mpv desktop='^6' follow=on focus=on
bspc rule -a Ghb desktop='^6' follow=on focus=on
bspc rule -a Xfburn desktop='^6' follow=on focus=on

## workspace 7 (graphics-editors)
bspc rule -a Gimp desktop='^7' follow=on focus=on
bspc rule -a Gimp-2.8 desktop='^7' follow=on focus=on
bspc rule -a Inkscape desktop='^7' follow=on focus=on
bspc rule -a Oomox desktop='^7' follow=on focus=on
bspc rule -a Steam desktop='^7' state=floating focus=on

## workspace 8 (system-settings)
bspc rule -a Lxappearance desktop='^8' state=floating follow=on
bspc rule -a Xfce4-settings-manager desktop='^8' state=floating follow=on
bspc rule -a Lightdm-gtk-greeter-settings desktop='^8' state=floating follow=on
bspc rule -a System-config-printer.py desktop='^8' state=floating follow=on
bspc rule -a Lxtask desktop='^8' state=floating follow=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a Pavucontrol desktop='^8' state=floating follow=on
bspc rule -a Exo-helper-1 desktop='^8' state=floating follow=on
bspc rule -a Lxrandr desktop='^8' state=floating follow=on
bspc rule -a Arandr desktop='^8' state=floating follow=on
bspc rule -a Deluge desktop='^8' state=floating focus=on

## need to be floating
bspc rule -a Audacious state=floating follow=on
bspc rule -a Viewnior state=floating follow=on
#bspc rule -a feh state=floating follow=on
bspc rule -a Gpicview state=floating follow=on
bspc rule -a sayonara state=floating manage=on
bspc rule -a Steam state=floating manage=on
bspc rule -a konsole state=floating manage=on
bspc rule -a Tilix state=floating manage=on
bspc rule -a virtualbox state=floating manage=on
bspc rule -a XTerm state=floating manage=on
#bspc rule -a Xterm:xdg-su state=floating manage=on

## don't manage my conky & systemtray :/
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off


###############
## autostart ##
###############

#Nitrogen
pkill nitrogen
nitrogen --restore &

#xxkb
pkill setxkbmap
#pkill xxkb
setxkbmap -layout us,ru -option grp:caps_toggle &

# Load bitmap fonts
xset fp+ ~/.fonts/misc &

## reload compton
pkill compton
compton --config ~/.config/compton/compton.conf -b &

#pkill numlockx
numlockx &
# system tray
#pkill stalonetray
#stalonetray &

# network applet
pkill nm-applet
nm-applet &

# clipboard manager
pkill clipit
clipit &

# volume icon
#pkill kmix
#kmix &

# keybind daemon
pkill sxhkd
sxhkd &

## music is my only friend :(
#mpd &

## reload the xsettingsd, a minimal x settings daemon
pkill xsettingsd
xsettingsd &

## set the wallpaper
#feh --bg-fill ~/.wallpaper.jpg

## load notify
pkill dunst
dunst &
#home/zulu/.config/dunst/valume.sh &

## reload the cursor theme
xsetroot -cursor_name left_ptr &

## load panel script
#pkill lemonbar
#~/.config/bspwm/bar/panel-bspwm | lemonbar -p &

## or polybar?
pkill polybar
polybar -c ~/.config/polybar/polybar top &

## load tint2
#pkill tint2
#tint2 &
